# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f815f5d34e1fcc4c47aeda37b0c4b41d5c3e80556f43aa7051f54e55eb317d71145a2f84857491e0437c26e29e971b25939c25cc4c57779d86f103c4593f1984

test:
  secret_key_base: 10a81a027e512bab71bcf3fd31bf05e9700c71f416ae2c30a0c46df3e8a498233c48632ed10f513dce55c2fcf98c2c139433c20baaed66c1a4a07fe8374ea57d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
